zex:
  host: "0.0.0.0"
  port: 15782
  api_prefix: "/v1"
  light_node: true
  state_source: "http://zex-state/zex_state.pb"
  state_dest: zex_state.pb
  state_save_frequency: 1000000
  tx_transmit_delay: 0.01
  mainnet: false
  verbose: true
  fill_dummy: true
  sequencer_mode: "local" # "eigenlayer", "docker"

  keys:
    deposit_public_key: 382892429471464219867747969662311867114742460359035433268305162405387427562199
    deposit_shield_address: "0xFB6E059Cc3F3E8029A2b25fE1fb1d952572f4181"
    btc_public_key: 0290ab36a28c3107d0091e8ea731e3c528046e317f854ed7b35f746d4e3484b1b3

  deployer_address: "0xa16aF858AEfE32994dAcdb640683a66FDcCB9569"
  byte_code_hash: "0x972b0e0eafa2adb02ebf7b1a35917a9114211a8e393a2ac373b8af263225f0f8"

  chains:
    - HOL
    - SEP
    - BST

  usdt_mainnet: "zUSDT"

  verified_tokens:
    zUSDT:
      HOL:
        contract_address: "0x325CCd77e71Ac296892ed5C63bA428700ec0f868"
        balance_withdraw_limit: 1
        decimal: 6
      SEP:
        contract_address: "0x325CCd77e71Ac296892ed5C63bA428700ec0f868"
        balance_withdraw_limit: 1
        decimal: 6
      BST:
        contract_address: "0x325CCd77e71Ac296892ed5C63bA428700ec0f868"
        balance_withdraw_limit: 1
        decimal: 6
    zEIGEN:
      HOL:
        contract_address: "0x219f1708400bE5b8cC47A56ed2f18536F5Da7EF4"
        balance_withdraw_limit: 0.01
        decimal: 18
      SEP:
        contract_address: "0x219f1708400bE5b8cC47A56ed2f18536F5Da7EF4"
        balance_withdraw_limit: 0.01
        decimal: 18
      BST:
        contract_address: "0x219f1708400bE5b8cC47A56ed2f18536F5Da7EF4"
        balance_withdraw_limit: 0.01
        decimal: 18
    zWBTC:
      HOL:
        contract_address: "0x9d84f6e4D734c33C2B6e7a5211780499A71aEf6A"
        balance_withdraw_limit: 0.00001
        decimal: 8
      SEP:
        contract_address: "0x9d84f6e4D734c33C2B6e7a5211780499A71aEf6A"
        balance_withdraw_limit: 0.00001
        decimal: 8
      BST:
        contract_address: "0x9d84f6e4D734c33C2B6e7a5211780499A71aEf6A"
        balance_withdraw_limit: 0.00001
        decimal: 8
